version : "3"
services:
  database:
    build:
      context: ./
      dockerfile: ./mysql.dockerfile
      args:
        MYSQL_ROOT_PASSWORD: 'testing-db-password'
    environment:
      MYSQL_DATABASE: 'testing-db'
      MYSQL_USER: 'testing-db-user'
      MYSQL_PASSWORD: 'testing-db-password'
      MYSQL_ROOT_PASSWORD: 'testing-db-password'
    ports:
      - '3309:3306' # <Port exposed> : < MySQL Port running inside container>
    expose:
      - 3309
    volumes:
      - ./db:/var/lib/mysql